apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moden-stats
  namespace: ethercluster
  labels:
    app: morden-stats
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: morden-stats
  template:
    metadata:
      name: morden-stats
      labels:
        app: morden-stats
    spec:
      containers:
      - name: ethstats
        image: ethereumex/eth-stats-dashboard:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: WS_SECRET
          valueFrom:
            secretKeyRef:
              name: morden-stats
              key: WS_SECRET
        ports:
        - containerPort: 3000
