apiVersion: v1
kind: PersistentVolume
metadata:
    name: kotti-persistent-volume
    namespace: ethercluster
spec:
    capacity:
        storage: 300Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        path: /var/nfs/kotti
