apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: classic-stats
  namespace: ethercluster
  labels:
    app: classic-stats
spec:
  replicas: 1
  template:
    metadata:
      name: classic-stats
      labels:
        app: classic-stats
    spec:
      containers:
      - name: ethstats
        image: etccoop/ethstats
        env:
        - name: WS_SECRET
          value: "12qw34er"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          timeoutSeconds: 5
