apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: classic 
  namespace: ethercluster
  labels:
    app: classic
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: classic
  serviceName: classic
  template:
    metadata:
      name: classic
      labels:
        app: classic
    spec:
      containers:
        - name: parity
          image: "etccoop/parity:latest"
          imagePullPolicy: Always
          args:
          - "--chain=classic"
          #- "--base-path=/parity-data"
          #- "--db-path=/parity-data/chains" 
          #- "--keys-path=/parity-data/keys"
          - "--jsonrpc-port=8545"
          - "--jsonrpc-interface=0.0.0.0"
          - "--jsonrpc-apis=web3,eth,net"
          - "--jsonrpc-hosts=all"
          ports:
            - containerPort: 8545
              protocol: TCP
              name: rpc-port
            - containerPort: 443
              protocol: TCP
              name: https
          readinessProbe:
            tcpSocket:
              port: 8545
            initialDelaySeconds: 60
          livenessProbe:
            tcpSocket:
              port: 8545
            initialDelaySeconds: 60
          volumeMounts:
            - name: classic-config
              mountPath: /classic-config
              readOnly: true
            - name: classic-data
              mountPath: /classic-data
        - name: liveness
          image: "yzhang1994/eth-node-checker"
          imagePullPolicy: IfNotPresent
          command: ["npm"]
          args: ["start"]
          env:
            - name: "WEB3_URL"
              value: "http://localhost:8545"
        - name: ethnetintel
          image: kairen/ethnetintel
          env:
          - name: NAME_PREFIX
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: WS_SERVER
            value: "104.198.240.121:3000"
          - name: WS_SECRET
            value: "12qw34er"
          - name: RPC_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: RPC_PORT
            value: "8545"
      volumes:
      - name: classic-config
        secret:
          secretName: classic-config
  volumeClaimTemplates:
    - metadata:
        name: classic-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "classic-ssd"
        resources:
          requests:
            storage: 50Gi
