apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kotti 
  namespace: ethercluster 
  labels:
    app: kotti
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: kotti
  serviceName: kotti
  template:
    metadata:
      name: kotti
      labels:
        app: kotti
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: parity
          image: "etccoop/parity:latest"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          args:
          - "--chain=kotti"
          - "--base-path=/kotti-data"
          - "--db-path=/kotti-data/chains" 
          - "--keys-path=/kotti-data/keys"
          - "--jsonrpc-port=8545"
          - "--jsonrpc-interface=0.0.0.0"
          - "--jsonrpc-apis=web3,eth,net,rpc,parity"
          - "--jsonrpc-hosts=all"
          ports:
            - containerPort: 8545
              protocol: TCP
              name: rpc-port
            - containerPort: 443
              protocol: TCP
              name: https
          readinessProbe:
            httpGet:
              port: 8545
              path: /api/health
            initialDelaySeconds: 1800
            periodSeconds: 60
          livenessProbe:
            httpGet:
              port: 8545
              path: /api/health
            initialDelaySeconds: 1800
            periodSeconds: 60
          volumeMounts:
            - name: kotti-config
              mountPath: /kotti-config
              readOnly: true
            - name: kotti-data
              mountPath: /kotti-data
        - name: liveness
          image: "yzhang1994/eth-node-checker"
          imagePullPolicy: IfNotPresent
          command: ["npm"]
          args: ["start"]
          env:
            - name: "WEB3_URL"
              value: "http://localhost:8545"
        - name: ethnetintel
          image: kairen/ethnetintel
          env:
          - name: NAME_PREFIX
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: WS_SERVER
            value: "104.198.240.121:3000"
          - name: WS_SECRET
            value: "12qw34er"
          - name: RPC_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: RPC_PORT
            value: "8545"
      volumes:
      - name: kotti-config
        secret:
          secretName: kotti-config
      - name: kotti-data
  volumeClaimTemplates:
    - metadata:
        name: kotti-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "kotti-ssd"
        resources:
          requests:
            storage: 30Gi
