apiVersion: v1
kind: Service
metadata:
  name: morden-stats
  namespace: ethercluster
  labels:
    app: morden-stats
spec:
  type: LoadBalancer
  selector:
    app: morden-stats
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
