apiVersion: v1
kind: Service
metadata:
    name: nginx-ingress-service
    namespace: ingress-nginx
    labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: http
      nodePort: 31114
      port: 80
      protocol: TCP
      targetPort: 80
    - name: rpc-port
      nodePort: 31119
      port: 8545
      protocol: TCP
      targetPort: 80
    - name: https
      nodePort: 31149
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
      app: nginx-ingress
      component: controller
      release: nginx-ingress
    sessionAffinity: None
    type: LoadBalancer
