apiVersion: v1
kind: Service
metadata:
  name: morden-stats
  namespace: ethercluster
  labels:
    app: morden-stats
spec:
  type: ClusterIP 
  selector:
    app: morden-stats
  ports:
  - port: 80
    targetPort: 3000
