apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: ingress-parity
    namespace: parity
    annotations:
        #nginx.ingress.kubernetes.io/rewrite-target: /
        kubernetes.io/ingress.global-static-ip-name: ethercluster-1
spec:
    tls:
      secretName: tls-classic
    rules:
    - http:
        paths:
        - path: /*
          backend:
            serviceName: parity 
            servicePort: 8545
