apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nginx-ingress-service
    namespace: ingress-nginx
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    tls:
    - hosts:
      - rpc.ethercluster.com
      secretName: tls-classic
    rules:
    - host: rpc.ethercluster.com 
      http:
        paths:
        - path: /
          backend:
            serviceName: nginx-ingress-service 
            servicePort: 8545
