apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: classic-ingress
  namespace: parity
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: tls-classic
    hosts:
    - rpc.ethercluster.com
  rules:
  - host: rpc.ethercluster.com
    http:
      paths:
      - path: /
        backend:
          serviceName: parity
          servicePort: 8545
