--
apiVersion: v1
kind: PersistentVolume
metadata:
    name: parity-persistent-volume
spec:
    capacity:
        storage: 300Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
        path: /var/nfs/parity
