apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: parity
  namespace: parity
  labels:
    app: parity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: parity
  serviceName: parity
  template:
    metadata:
      name: parity
      labels:
        app: parity
    spec:
      containers:
        - name: parity
          image: "parity/parity:stable"
          imagePullPolicy: IfNotPresent
          args:
          - "--chain=classic"
          - "--base-path=/parity-data"
          - "--db-path=/parity-data/chains"
          - "--keys-path=/parity-data/keys"
          - "--interface=0.0.0.0"
          ports:
            - containerPort: 8545
              protocol: TCP
              name: rpc-port
          livenessProbe:
            tcpSocket:
              port: 8545
            initialDelaySeconds: 60
          volumeMounts:
            - name: parity-config
              mountPath: /parity-config
              readOnly: true
            - name: parity-data
              mountPath: /parity-data
      volumes:
      - name: parity-config
        secret:
          secretName: parity-config
  volumeClaimTemplates:
    - metadata:
        name: parity-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "classic-ssd"
        resources:
          requests:
            storage: 50Gi
   - metadata:
       name: parity-config
     spec:
       accessModes: ["ReadOnlyMany"]
       storageClassName: "classic-ssd"
       resources:
         requests:
           storage: 1Gi
