apiVersion: v1
kind: Service
metadata:
  labels:
    app: morden 
  name: morden 
  namespace: ethercluster
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  selector:
    app: morden 
  ports:
  - name: default
    protocol: TCP
    port:  8080 
    targetPort: 8080
  - name: rpc-endpoint
    port: 8545 
    protocol: TCP
    targetPort: 8545
  - name: https
    port: 443 
    protocol: TCP
    targetPort: 443
  type: LoadBalancer
  sessionAffinity: ClientIP
